# Generated by Django 6.0.3 on 2026-05-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto_criado', 'Produto criado'), ('produto_editado', 'Produto editado'), ('produto_deletado', 'Produto deletado'), ('login', 'Login'), ('registro', 'Registro'), ('pedido_criado', 'Pedido criado'), ('pedido_deletado', 'Pedido deletado')], max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
